import './Checkbox/MDCCheckbox.razor.js'
import './CircularProgress/MDCCircularProgress.razor.js'
import './Drawer/MDCDrawer.razor.js'
import './List/MDCList.razor.js'
import './Select/MDCSelect.razor.js'
import './Snackbar/MDCSnackbar.razor.js'
import './TabBar/MDCTabBar.razor.js'
import './TopAppBar/MDCTopAppBar.razor.js'
